weather:
  latitude: 44.9916
  longitude: -93.4053

anthropic:
  api-key: ${ANTHROPIC_API_KEY:}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/menu_planner
    username: menu_user
    password: menu_pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
