--liquibase formatted sql

--changeset rachel:001-initial-schema
CREATE TABLE household (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE app_user (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(255),
    email         varchar(255),
    password_hash varchar(255),
    household_id  bigint REFERENCES household(id),
    CONSTRAINT app_user_email_unique UNIQUE (email)
);

CREATE TABLE meal (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255),
    recipe_link  varchar(255),
    notes        varchar(255),
    household_id bigint REFERENCES household(id),
    shared       boolean NOT NULL DEFAULT false,
    min_temp     integer,
    max_temp     integer,
    seasons      varchar(50)
);

CREATE TABLE menu_entry (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_date          date,
    day_of_week        varchar(255),
    confirmed          boolean,
    leftover           boolean,
    leftover_from_date date,
    meal_id            bigint REFERENCES meal(id),
    household_id       bigint REFERENCES household(id)
);

CREATE TABLE weather_record (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       date,
    condition  varchar(255),
    high_tempf integer,
    low_tempf  integer,
    CONSTRAINT weather_record_date_unique UNIQUE (date)
);
--rollback DROP TABLE weather_record; DROP TABLE menu_entry; DROP TABLE meal; DROP TABLE app_user; DROP TABLE household;
