--liquibase formatted sql

--changeset rachel:005-add-recipe-ingredient-side-tables
CREATE TABLE ingredient (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) NOT NULL,
    household_id bigint REFERENCES household(id)
);

CREATE TABLE side (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) NOT NULL,
    household_id bigint REFERENCES household(id)
);

CREATE TABLE recipe (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id      bigint UNIQUE REFERENCES meal(id),
    name         varchar(255) NOT NULL,
    instructions text
);

CREATE TABLE recipe_ingredient (
    recipe_id     bigint REFERENCES recipe(id),
    ingredient_id bigint REFERENCES ingredient(id),
    PRIMARY KEY (recipe_id, ingredient_id)
);

CREATE TABLE meal_side (
    meal_id bigint REFERENCES meal(id),
    side_id bigint REFERENCES side(id),
    PRIMARY KEY (meal_id, side_id)
);
