--liquibase formatted sql

--changeset rachel:008-seed-global-ingredients
INSERT INTO ingredient (name, household_id) VALUES
-- Vegetables
('artichoke', NULL),
('arugula', NULL),
('asparagus', NULL),
('avocado', NULL),
('baby spinach', NULL),
('bamboo shoots', NULL),
('beet', NULL),
('bell pepper', NULL),
('bok choy', NULL),
('broccoli', NULL),
('broccoli rabe', NULL),
('brussels sprouts', NULL),
('butternut squash', NULL),
('cabbage', NULL),
('carrot', NULL),
('cauliflower', NULL),
('celery', NULL),
('celery root', NULL),
('chard', NULL),
('chili pepper', NULL),
('collard greens', NULL),
('corn', NULL),
('cucumber', NULL),
('eggplant', NULL),
('endive', NULL),
('fennel', NULL),
('garlic', NULL),
('ginger', NULL),
('green beans', NULL),
('green cabbage', NULL),
('green onion', NULL),
('jalapeño', NULL),
('jicama', NULL),
('kale', NULL),
('leek', NULL),
('lettuce', NULL),
('mushroom', NULL),
('napa cabbage', NULL),
('okra', NULL),
('onion', NULL),
('parsnip', NULL),
('peas', NULL),
('poblano pepper', NULL),
('potato', NULL),
('pumpkin', NULL),
('radicchio', NULL),
('radish', NULL),
('red cabbage', NULL),
('red onion', NULL),
('romaine lettuce', NULL),
('rutabaga', NULL),
('serrano pepper', NULL),
('shallot', NULL),
('snow peas', NULL),
('spinach', NULL),
('sugar snap peas', NULL),
('summer squash', NULL),
('sweet potato', NULL),
('tomato', NULL),
('turnip', NULL),
('water chestnuts', NULL),
('watercress', NULL),
('yellow onion', NULL),
('yellow squash', NULL),
('zucchini', NULL),
-- Fruits
('apple', NULL),
('apricot', NULL),
('banana', NULL),
('blackberry', NULL),
('blueberry', NULL),
('cantaloupe', NULL),
('cherry', NULL),
('clementine', NULL),
('coconut', NULL),
('cranberry', NULL),
('date', NULL),
('fig', NULL),
('grape', NULL),
('grapefruit', NULL),
('honeydew', NULL),
('kiwi', NULL),
('lemon', NULL),
('lime', NULL),
('mango', NULL),
('nectarine', NULL),
('orange', NULL),
('papaya', NULL),
('passion fruit', NULL),
('peach', NULL),
('pear', NULL),
('pineapple', NULL),
('plum', NULL),
('pomegranate', NULL),
('raspberry', NULL),
('strawberry', NULL),
('watermelon', NULL),
-- Proteins — Meat
('bacon', NULL),
('beef brisket', NULL),
('beef chuck', NULL),
('chicken breast', NULL),
('chicken thigh', NULL),
('chorizo', NULL),
('ground beef', NULL),
('ground lamb', NULL),
('ground pork', NULL),
('ground turkey', NULL),
('ham', NULL),
('Italian sausage', NULL),
('lamb chop', NULL),
('lamb shoulder', NULL),
('pancetta', NULL),
('pepperoni', NULL),
('pork belly', NULL),
('pork chop', NULL),
('pork loin', NULL),
('pork shoulder', NULL),
('prosciutto', NULL),
('ribeye steak', NULL),
('salami', NULL),
('sausage', NULL),
('sirloin steak', NULL),
('veal', NULL),
('whole chicken', NULL),
-- Proteins — Seafood
('anchovy', NULL),
('clam', NULL),
('cod', NULL),
('crab', NULL),
('halibut', NULL),
('lobster', NULL),
('mussel', NULL),
('oyster', NULL),
('salmon', NULL),
('sardine', NULL),
('scallop', NULL),
('shrimp', NULL),
('tilapia', NULL),
('trout', NULL),
('tuna', NULL),
-- Proteins — Other
('egg', NULL),
('firm tofu', NULL),
('lentils', NULL),
('silken tofu', NULL),
('tempeh', NULL),
-- Dairy
('butter', NULL),
('buttermilk', NULL),
('cheddar cheese', NULL),
('cottage cheese', NULL),
('cream', NULL),
('cream cheese', NULL),
('feta cheese', NULL),
('goat cheese', NULL),
('gouda cheese', NULL),
('gruyère cheese', NULL),
('half and half', NULL),
('heavy cream', NULL),
('mascarpone', NULL),
('milk', NULL),
('monterey jack cheese', NULL),
('mozzarella cheese', NULL),
('parmesan cheese', NULL),
('provolone cheese', NULL),
('ricotta cheese', NULL),
('romano cheese', NULL),
('sour cream', NULL),
('swiss cheese', NULL),
('whipped cream', NULL),
('whole milk', NULL),
('yogurt', NULL),
-- Grains & Pasta
('arborio rice', NULL),
('barley', NULL),
('bread crumbs', NULL),
('brown rice', NULL),
('buckwheat', NULL),
('bulgur', NULL),
('couscous', NULL),
('egg noodles', NULL),
('farro', NULL),
('fettuccine', NULL),
('jasmine rice', NULL),
('lasagna noodles', NULL),
('linguine', NULL),
('oats', NULL),
('orzo', NULL),
('penne', NULL),
('polenta', NULL),
('quinoa', NULL),
('rice noodles', NULL),
('rigatoni', NULL),
('spaghetti', NULL),
('white rice', NULL),
('whole wheat pasta', NULL),
-- Legumes
('black beans', NULL),
('black-eyed peas', NULL),
('cannellini beans', NULL),
('chickpeas', NULL),
('edamame', NULL),
('green lentils', NULL),
('kidney beans', NULL),
('lima beans', NULL),
('navy beans', NULL),
('pinto beans', NULL),
('red lentils', NULL),
('split peas', NULL),
-- Nuts & Seeds
('almond', NULL),
('cashew', NULL),
('chia seeds', NULL),
('flaxseed', NULL),
('hemp seeds', NULL),
('macadamia nut', NULL),
('peanut', NULL),
('pecan', NULL),
('pine nut', NULL),
('pistachio', NULL),
('poppy seeds', NULL),
('pumpkin seeds', NULL),
('sesame seeds', NULL),
('sunflower seeds', NULL),
('walnut', NULL),
-- Baking
('all-purpose flour', NULL),
('almond flour', NULL),
('baking powder', NULL),
('baking soda', NULL),
('bread flour', NULL),
('brown sugar', NULL),
('cake flour', NULL),
('cocoa powder', NULL),
('cornmeal', NULL),
('cornstarch', NULL),
('cream of tartar', NULL),
('granulated sugar', NULL),
('honey', NULL),
('maple syrup', NULL),
('molasses', NULL),
('powdered sugar', NULL),
('vanilla extract', NULL),
('whole wheat flour', NULL),
('yeast', NULL),
-- Herbs (fresh & dried)
('basil', NULL),
('bay leaf', NULL),
('chives', NULL),
('cilantro', NULL),
('dill', NULL),
('dried oregano', NULL),
('dried rosemary', NULL),
('dried sage', NULL),
('dried thyme', NULL),
('fresh mint', NULL),
('fresh oregano', NULL),
('fresh rosemary', NULL),
('fresh sage', NULL),
('fresh thyme', NULL),
('lemongrass', NULL),
('marjoram', NULL),
('parsley', NULL),
('tarragon', NULL),
-- Spices
('allspice', NULL),
('black pepper', NULL),
('cardamom', NULL),
('cayenne pepper', NULL),
('chili flakes', NULL),
('chili powder', NULL),
('cinnamon', NULL),
('cloves', NULL),
('coriander', NULL),
('cumin', NULL),
('curry powder', NULL),
('fennel seeds', NULL),
('five spice powder', NULL),
('garam masala', NULL),
('garlic powder', NULL),
('ground ginger', NULL),
('mustard powder', NULL),
('nutmeg', NULL),
('onion powder', NULL),
('paprika', NULL),
('red pepper flakes', NULL),
('salt', NULL),
('smoked paprika', NULL),
('star anise', NULL),
('turmeric', NULL),
('white pepper', NULL),
-- Oils & Fats
('avocado oil', NULL),
('canola oil', NULL),
('coconut oil', NULL),
('olive oil', NULL),
('sesame oil', NULL),
('vegetable oil', NULL),
-- Vinegars & Acids
('apple cider vinegar', NULL),
('balsamic vinegar', NULL),
('lemon juice', NULL),
('lime juice', NULL),
('red wine vinegar', NULL),
('rice vinegar', NULL),
('white wine vinegar', NULL),
-- Condiments & Sauces
('fish sauce', NULL),
('hot sauce', NULL),
('ketchup', NULL),
('mayonnaise', NULL),
('mustard', NULL),
('oyster sauce', NULL),
('soy sauce', NULL),
('sriracha', NULL),
('tahini', NULL),
('teriyaki sauce', NULL),
('tomato paste', NULL),
('tomato sauce', NULL),
('Worcestershire sauce', NULL),
-- Stocks & Broths
('beef broth', NULL),
('chicken broth', NULL),
('chicken stock', NULL),
('fish stock', NULL),
('vegetable broth', NULL),
-- Canned & Pantry
('black olives', NULL),
('capers', NULL),
('canned coconut milk', NULL),
('canned diced tomatoes', NULL),
('canned whole tomatoes', NULL),
('chipotle in adobo', NULL),
('crushed tomatoes', NULL),
('green olives', NULL),
('kalamata olives', NULL),
('roasted red peppers', NULL),
('sun-dried tomatoes', NULL),
-- Wine & Spirits (cooking)
('dry red wine', NULL),
('dry sherry', NULL),
('dry white wine', NULL),
('mirin', NULL),
('rice wine', NULL),
-- Bread & Misc
('baguette', NULL),
('brioche', NULL),
('pita bread', NULL),
('sourdough bread', NULL),
('tortilla', NULL),
('white bread', NULL),
('whole wheat bread', NULL)
ON CONFLICT DO NOTHING;
