--liquibase formatted sql

--changeset rachel:009-add-cookbook
CREATE TABLE cookbook (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) NOT NULL,
    household_id bigint REFERENCES household(id)
);

ALTER TABLE recipe ADD COLUMN cookbook_id bigint REFERENCES cookbook(id);
