--liquibase formatted sql
--changeset rachel:015-add-pantry-item-table
CREATE TABLE pantry_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    household_id BIGINT NOT NULL,
    FOREIGN KEY (household_id) REFERENCES household(id)
);
